vim.cmd('autocmd VimEnter * highlight LineNr guifg=#c0c0c0')
vim.cmd('autocmd VimEnter * highlight CursorLine term=bold cterm=bold guibg=#2f4f4f')
vim.cmd('autocmd VimEnter * highlight ColorColumn ctermbg=lightgrey guibg=#8c0000')
vim.cmd('autocmd VimEnter * highlight Visual guifg=black guibg=Yellow guifg=none')
vim.cmd('autocmd VimEnter * highlight Comment guifg=#228B22')
vim.cmd('set cursorline')
vim.cmd('set colorcolumn=80')
